### ISSUE TITLE
Problem with encode_img() function in aee.py

### ISSUE THREAD

**Issue by vinisalazar** [divelab/cgan#3]
Hi, I'm trying to get your code to work but I get an error for an undefined name at line 63 in the `aee.py` file, more specifically the following line:  
`self.output_r, self.down_outputs = encode_img(self.input_x_r, self.conf.hidden_size)`  

It appears the `encode_img()` function is not defined.

**Comment by divelab** [comment]
Please read README before running the code.
"Set related arguments in main.py. There are three proposed skip connections, please choose the corresponding ops-XXX file and update the name to 'ops.py'."

**Comment by vinisalazar** [comment]
I suggest inserting a comment above this line explaining this method comes from the ops file.
